on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven

        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify

        - name: Copy packages to staging
          run: mkdir staging && cp target/*.war staging

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Package
            path: staging

  security:
  
      runs-on: ubuntu-latest
  
      permissions:
        security-events: write
  
  
      steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/maven-3-jdk-21@master
          continue-on-error: true # To make sure that SARIF upload gets called
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            args: --sarif-file-output=snyk.sarif --severity-threshold=low
        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: snyk.sarif
        