on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
        
        - name: Run Snyk to check for vulnerabilities
          uses: actions/checkout@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            args: --severity-threshold=low

        - name: Build with Maven
          run: mvn clean --batch-mode --update-snapshots verify

        - name: Copy packages to staging
          run: mkdir staging && cp target/*.war staging

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Package
            path: staging
        
        - name: Download and setup WildFly 
          run: |
            WILDFLY_VERSION=37.0.1.Final
            wget https://github.com/wildfly/wildfly/releases/download/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz
            tar -xzf wildfly-$WILDFLY_VERSION.tar.gz
            echo "$HOME/wildfly-$WILDFLY_VERSION/bin" >> $GITHUB_PATH

        - name: Deploy using CLI
          run: |
            jboss-cli.sh --connect --controller=${{ secrets.WILDFLY_HOST }}:9990 \
              --user=${{ secrets.WILDFLY_USERNAME }} \
              --password=${{ secrets.WILDFLY_PASSWORD }} \
              --command="deploy staging/*.war --force"
