on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
            
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify

        - name: Copy packages to staging
          run: mkdir staging && cp target/*.war staging

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: Package
            path: staging
        